export const LOCAL_STORAGE_KEYS = {
  FLOWBUILD_SERVER: 'FLOWBUILD_SERVER',
  FLOWBUILD_PORT: 'FLOWBUILD_PORT',
  MQTT_SERVER: 'MQTT_SERVER',
  MQTT_PORT: 'MQTT_PORT',
  MQTT_NAMESPACE: 'MQTT_NAMESPACE',
  MQTT_USERNAME: 'MQTT_USERNAME',
  MQTT_PASSWORD: 'MQTT_PASSWORD'
} as const;
