export const LOCAL_STORAGE_KEYS = {
  FLOWBUILD_SERVER: 'FLOWBUILD_SERVER',
  FLOWBUILD_PORT: 'FLOWBUILD_PORT',
  METABASE_URL: 'METABASE_URL',
  METABASE_SECRET_KEY: 'METABASE_SECRET_KEY',
  METABASE_DASHBOARD_ID: 'METABASE_DASHBOARD_ID',
  METABASE_DASHBOARD_REPORT_URL: 'METABASE_DASHBOARD_REPORT_URL'
} as const;
